### ISSUE TITLE
Investigate bridge losing connection to NATS

### ISSUE THREAD

**Issue by abey-yoseph** [usdot-fhwa-stol/cda-telematics#150]
### Summary

During the verification testing, an additional test case was added involving the Tahoe at Suntrax. The Tahoe was able to successfully stream data for a period of time, but at some point it lost connection to NATS. The bridge logs show the bridge publishing data to NATS, and then getting disconnected to NATs. After losing connection, it seems that the bridge repeatedly tries to connect to NATS but never succeeds. Need to bench test this scenario and implement fix if necessary. 

![tahoenatsissue](https://github.com/usdot-fhwa-stol/cda-telematics/assets/59704440/0ae6c0b2-2d40-4434-b726-9786710e655a)

### Version

4.3.0 (Current)

### Expected Behavior

Bridge should successfully reconnect to NATS and begin publishing messages again.

### Actual Behavior

Bridge lost connection to NATs and failed to reconnect.

### Steps to Reproduce the Actual Behavior

Would have to bring up a bridge unit and purposefully disconnect from cellular/Wi-Fi, so it can't communicate with the remote NATS server.

**Comment by adev4a** [comment]
Data streaming was tested on the Tahoe at ACM and this issue was not seen again
