### ISSUE TITLE
Update carma config for telematics with the latest simulation setup used in VRU use case 1

### ISSUE THREAD

**Issue by dan-du-car** [usdot-fhwa-stol/cda-telematics#207]
### Summary

- Need to fix the internal CARMA ROS1, ROS2 components communication issue with RMW_IMPLEMENTATION.
- Update .env file in the cdasim config with complete DOCKER_* related information.
- Copy cdasim_config from VRU use case 1
- Fix issues launching latest develop version CARMA platform in simulation environment.

### Commit

NA

### Expected Behavior

CARMA Platform run VRU use case 1 scenario without issue in simulation (XiL) environment.

### Actual Behavior

CARMA Platform ROS2 failed and cannot engage vehicle in simulation environment

### Steps to Reproduce the Actual Behavior

Refer to setup instruction: https://usdot-carma.atlassian.net/wiki/spaces/WFD2/pages/2907996170/Development+Environment+setup+-+Telematics+tool+XiL+integration+test

### Related Work

https://github.com/usdot-fhwa-stol/carma-config/pull/347

**Comment by adev4a** [comment]
Resolved by https://github.com/usdot-fhwa-stol/carma-config/pull/347
