### ISSUE TITLE
Historical processing service: Invalid literal for int with {DB_PORT}

### ISSUE THREAD

**Issue by dan-du-car** [usdot-fhwa-stol/cda-telematics#216]
### Summary

Cannot launch historical processing service because it cannot read database port. Detail of this issue, see below:

![image](https://github.com/usdot-fhwa-stol/cda-telematics/assets/62157949/e2c37340-3bf9-470d-a050-51caa4ecd90b)

### Commit

NA

### Expected Behavior

Can launch historical processing service without issue.

### Actual Behavior

Cannot launch historical processing service because it cannot read database port.

### Steps to Reproduce the Actual Behavior

`docker-compose -f docker-compose.historical.yml up`

**Comment by adev4a** [comment]
Closed by #217
